#!/bin/bash

set -e

DIR=$(dirname "$(readlink -f "$0")")
GIT_CHANGES=$(git diff --name-only --cached)

has_changed() {
    echo $GIT_CHANGES | grep "$1" > /dev/null 2>&1
}

if has_changed ".*\.php$"; then
    for file in $GIT_CHANGES; do
        if [[ $file != *.php ]]; then
            continue
        fi

        php -l $file
    done
fi
