runtime: custom

env_variables:
  DEBUG: 0

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 3
  healthy_threshold: 2
  restart_threshold: 10

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 3
#  cool_down_period_sec: 180
#  cpu_utilization:
#    target_utilization: 0.7

#readiness_check:
#  path: "/readiness_check"
#  check_interval_sec: 5
#  timeout_sec: 4
#  failure_threshold: 2
#  success_threshold: 2
#  app_start_timeout_sec: 300

#liveness_check:
#  path: "/liveness_check"
#  check_interval_sec: 30
#  timeout_sec: 4
#  failure_threshold: 2
#  success_threshold: 2

#error_handlers:
#  - file: default_error.html
#
#  - error_code: over_quota
#    file: over_quota.html
#
#  - error_code: dos_api_denial
#    file: dos_api_denial.html
#
#  - error_code: timeout
#    file: timeout.html

#resources:
#  cpu: 2
#  memory_gb: 2.3
#  disk_size_gb: 10
#  volumes:
#  - name: ramdisk1
#    volume_type: tmpfs
#    size_gb: 0.5

#network:
#  instance_tag: TAG_NAME
#  name: NETWORK_NAME
#  subnetwork_name: SUBNETWORK_NAME
#  forwarded_ports:
#    - PORT
#    - HOST_PORT:CONTAINER_PORT
#    - PORT/tcp
#    - HOST_PORT:CONTAINER_PORT/udp
