version: '3'
services:
  web:
    build: .
    image: coisa/skeleton
    hostname: web.local
    ports:
      - 80:80
    env_file: .env
    volumes:
      - ./:/opt/project
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.6
    hostname: mysql.local
    env_file: .env

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq.local
    ports:
      - 15672:15672
    env_file: .env

  redis:
    image: redis