version: '3'
services:
  web:
    build: .
    image: coisa/sandbox
    hostname: web
    ports:
      - 80:80
    env_file: .env
    volumes:
      - ./:/opt/project
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.6
    hostname: mysql
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    env_file: .env
    links:
      - mysql:db
    ports:
      - 8080:80

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq.local
    ports:
      - 15672:15672
    env_file: .env

  redis:
    image: redis
